spotifyQueries = [
  "How do I get back into my account if I forgot the password?",
  "Why isn’t my playlist showing up on my other devices?",
  "How can I stop songs from playing automatically after my playlist ends?",
  "Why do I keep hearing ads even though I paid for Premium?",
  "How can I find songs I recently played?",
  "What’s the easiest way to share a playlist with a friend?",
  "How do I make my playlists private so no one can see them?",
  "Why is my music stopping when I switch apps?",
  "How do I save data when using Spotify on my phone?",
  "Why can’t I find certain songs or albums?",
  "What’s the deal with 'Spotify Wrapped'? How do I see mine?",
  "How do I get better sound quality on my Spotify?",
  "Can I play Spotify on my TV? How?",
  "Why is the app asking me to update my payment info?",
  "How do I add a new card for my subscription?",
  "Why can’t I skip songs anymore?",
  "How do I turn on shuffle?",
  "How can I connect Spotify to my Alexa or Google Home?",
  "Why isn’t my music playing through Bluetooth in my car?",
  "How do I download songs to listen without Wi-Fi?",
  "What happened to the lyrics feature? I can’t see it anymore.",
  "How do I add a song to a playlist while I’m listening?",
  "Why can’t my family member join my Premium Family plan?",
  "How do I stop Spotify from using so much storage on my phone?",
  "Why is the app saying I’m logged in on another device?",
  "How can I see what my friends are listening to?",
  "What’s the best way to organize my playlists?",
  "How do I listen to podcasts on Spotify?",
  "Can I make my playlist so other people can add songs?",
  "Why can’t I find my Daily Mix?",
  "How do I restart my Discover Weekly recommendations?",
  "How do I get rid of a song I don’t like from my playlist?",
  "Why is Spotify asking for my location?",
  "Can I listen to music with a friend at the same time?",
  "How do I check how much time I’ve spent listening to Spotify?",
  "Why is Spotify so slow on my phone?",
  "How do I fix it if Spotify keeps crashing?",
  "How do I move all my playlists to a new account?",
  "Why isn’t Spotify connecting to my Wi-Fi speaker?",
  "How do I see the top songs of an artist?",
  "How do I stop Spotify from playing explicit songs?",
  "How do I change the photo on my playlist?",
  "Why are the same songs repeating on my playlist?",
  "How can I skip to a specific part of a podcast episode?",
  "How do I turn off notifications from Spotify?",
  "Why does the app keep logging me out?",
  "How do I keep Spotify running in the background?",
  "Why isn’t Spotify available in my country?",
  "How can I organize my downloaded music better?",
  "Why are some songs greyed out in my playlist?",
  "How do I add Spotify to my gaming console?",
  "How do I find my friends on Spotify?",
  "Why is my favorite artist’s new album not on Spotify?",
  "How do I block someone from seeing my profile?",
  "How can I see my most listened-to songs?",
  "What’s the difference between a playlist and a radio station?",
  "Why does Spotify keep pausing my music?",
  "How do I stop Spotify from suggesting songs I don’t like?",
  "How can I add a whole album to my playlist?",
  "Why does Spotify say I’ve reached a limit when adding songs?",
  "Can I stop people from following my playlists?",
  "How do I make a playlist for running or working out?",
  "How can I see how many times I’ve listened to a song?",
  "Why can’t I add more family members to my Premium plan?",
  "How do I report an issue with a song or podcast?",
  "Why can’t I fast-forward through ads?",
  "How do I set up Spotify on my Apple Watch?",
  "How can I tell which playlists are public?",
  "Why do I keep hearing the same songs on shuffle?",
  "How do I stop Spotify from using mobile data?",
  "Why are my downloaded songs disappearing?",
  "How can I move a song up or down in my playlist?",
  "Why isn’t Spotify updating the new songs I’ve added?",
  "How do I follow an artist to get updates on new music?",
  "How can I keep Spotify from crashing when I open another app?",
  "Why isn’t my Spotify Premium active after I paid?",
  "How do I connect Spotify to my smartwatch?",
  "Why can’t I see all my songs when I’m offline?",
  "How do I mute ads when I’m on the Free version?",
  "How do I combine two playlists into one?",
  "Can I make Spotify louder without using my phone’s volume?",
  "Why can’t I remove a song from my 'Liked Songs'?",
  "How do I fix Spotify if it’s not syncing with my computer?",
  "Why can’t I rewind a podcast episode?",
  "How can I see what I’ve queued up to play next?",
  "How do I remove a song from my 'Recently Played' list?",
  "Why is my Spotify Premium charging me twice?",
  "How do I change the order of songs in my playlist?",
  "Can I listen to Spotify while playing a game?",
  "How do I stop Spotify from playing videos?",
  "Why doesn’t my music start when I press play?",
  "How do I fix my Spotify account if I was hacked?",
  "How can I tell how many playlists I’ve made?",
  "Why isn’t my Spotify Wrapped available yet?",
  "How can I search for playlists by mood or activity?",
  "How do I fix the volume if it’s too quiet on Spotify?",
  "Why can’t I skip to the next song sometimes?",
  "How can I make my playlist play in the same order every time?",
  "What’s the best way to get Spotify on a new device?",
  "How do I stop Spotify from using battery when I’m not playing music?"
]
